#!/usr/bin/env python3
"""Emit a git-filter-repo --replace-text list for purging real lab data.

Run this *before* rewriting history. It harvests the confidential strings from
the repository's own history and from the local run folder, and prints
``literal:<secret>==>REDACTED`` lines.

**The output contains the confidential data.** Write it outside the repo, feed
it to git-filter-repo, then delete it:

    python tools/build_redactions.py > /tmp/redactions.txt
    git filter-repo --replace-text /tmp/redactions.txt --force
    rm /tmp/redactions.txt

See docs/anonymisation.md for the full procedure.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

from check_no_lab_data import IDENTIFIERS, SEQUENCE_FINGERPRINTS, SKIP_SUFFIXES

_ROOT = Path(__file__).resolve().parents[1]
#: Long biological strings are harvested wholesale; these set the floor.
MIN_AA, MIN_DNA = 40, 60
_AA = re.compile(r"\b[ACDEFGHIKLMNPQRSTVWY]{%d,}\b" % MIN_AA)
_DNA = re.compile(r"\b[ACGT]{%d,}\b" % MIN_DNA)


def historical_blobs():
    revs = subprocess.run(["git", "rev-list", "--all"], capture_output=True,
                          text=True, check=True).stdout.split()
    seen: set[str] = set()
    for rev in revs:
        names = subprocess.run(["git", "ls-tree", "-r", "--name-only", rev],
                               capture_output=True, text=True, check=True).stdout.split("\n")
        for name in names:
            if not name or name.endswith(SKIP_SUFFIXES):
                continue
            blob = subprocess.run(["git", "rev-parse", f"{rev}:{name}"],
                                  capture_output=True, text=True).stdout.strip()
            if blob and blob not in seen:
                seen.add(blob)
                yield subprocess.run(["git", "cat-file", "-p", blob],
                                     capture_output=True, text=True).stdout


def main() -> int:
    # Never redact what we deliberately keep: the synthetic examples and the
    # destination vectors (a cloning vector is not confidential design output).
    keep_text = [p.read_text(encoding="utf-8", errors="ignore")
                 for d in ("examples", "plasmids")
                 for p in (_ROOT / "data" / d).glob("*.fa")]
    synthetic: set[str] = set()
    for text in keep_text:
        flat = text.replace("\n", "").upper()
        synthetic |= set(_AA.findall(flat)) | set(_DNA.findall(flat))

    secrets: set[str] = set()
    for text in historical_blobs():
        flat = re.sub(r"[\s\"']", "", text).upper()
        for pattern in (_AA, _DNA):
            for hit in pattern.findall(flat):
                # Skip anything that is part of a sequence we are keeping.
                if hit in synthetic or any(hit in k for k in synthetic):
                    continue
                secrets.add(hit)

    # Short identifiers are replaced literally; sequences wholesale.
    print("# Generated by tools/build_redactions.py - DELETE AFTER USE",
          file=sys.stderr)
    for s in sorted(secrets, key=len, reverse=True):
        print(f"literal:{s}==>REDACTED_SEQUENCE")
    for ident in IDENTIFIERS:
        if ident == "Working folder":
            print("literal:Working folder==>data/runs")
        else:
            print(f"literal:{ident}==>REDACTED")
    for frag in SEQUENCE_FINGERPRINTS:
        print(f"literal:{frag}==>REDACTED_SEQUENCE")
    print(f"# {len(secrets)} harvested sequences + "
          f"{len(IDENTIFIERS) + len(SEQUENCE_FINGERPRINTS)} known patterns",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    raise SystemExit(main())
