#!/usr/bin/env python3
"""Emit a git-filter-repo --replace-text list for purging real lab data.

Run this *before* rewriting history. It harvests long biological sequences from
the repository's own history — everything that is not part of a file we
deliberately keep (`data/examples/`, `data/plasmids/`) — and prints
``literal:<secret>==>REDACTED_SEQUENCE`` lines.

Project and target *identifiers* are not harvested: this file is public, so it
cannot carry a list of them (see tools/check_no_lab_data.py for why). Append
those replacements yourself; the template at the end of the output shows the
format.

**The output contains the confidential sequences.** Write it outside the repo,
feed it to git-filter-repo, then delete it::

    python tools/build_redactions.py > /tmp/redactions.txt
    # edit /tmp/redactions.txt to add your identifier replacements
    git filter-repo --replace-text /tmp/redactions.txt --force
    rm /tmp/redactions.txt

See docs/anonymisation.md for the full procedure.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
SKIP_SUFFIXES = (".png", ".svg", ".xlsx", ".xls", ".pdf", ".ico", ".zip")
#: Long biological strings are harvested wholesale; these set the floor.
MIN_AA, MIN_DNA = 40, 60
_AA = re.compile(r"[ACDEFGHIKLMNPQRSTVWY]{%d,}" % MIN_AA)
_DNA = re.compile(r"[ACGT]{%d,}" % MIN_DNA)


def historical_blobs():
    revs = subprocess.run(["git", "rev-list", "--all"], capture_output=True,
                          text=True, check=True).stdout.split()
    seen: set[str] = set()
    for rev in revs:
        listing = subprocess.run(["git", "ls-tree", "-r", rev], capture_output=True,
                                 text=True, check=True).stdout.split("\n")
        for line in listing:
            if not line:
                continue
            meta, _, name = line.partition("\t")
            if name.endswith(SKIP_SUFFIXES):
                continue
            blob = meta.split()[2]
            if blob in seen:
                continue
            seen.add(blob)
            yield subprocess.run(["git", "cat-file", "-p", blob],
                                 capture_output=True, text=True).stdout


def main() -> int:
    # Never redact what we deliberately keep: the synthetic examples and the
    # destination vectors (a cloning vector is not confidential design output).
    keep: set[str] = set()
    for folder in ("examples", "plasmids"):
        for path in (_ROOT / "data" / folder).glob("*.fa"):
            flat = "".join(path.read_text(encoding="utf-8", errors="ignore").split()).upper()
            keep |= set(_AA.findall(flat)) | set(_DNA.findall(flat))

    secrets: set[str] = set()
    for text in historical_blobs():
        flat = re.sub(r"[\s\"']", "", text).upper()
        for pattern in (_AA, _DNA):
            for hit in pattern.findall(flat):
                if hit in keep or any(hit in k for k in keep):
                    continue
                secrets.add(hit)

    print("# Generated by tools/build_redactions.py - CONTAINS SECRETS, DELETE AFTER USE",
          file=sys.stderr)
    for secret in sorted(secrets, key=len, reverse=True):
        print(f"literal:{secret}==>REDACTED_SEQUENCE")
    print("\n***REMOVED***")
    print("REDACTED==>REDACTED")
    print("SetA==>SetA")
    print(f"# {len(secrets)} sequence(s) harvested from history.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
